=== TIBHannover/climate-knowledge-graph/data-import/XML-DTD/outputs-inc-dtd/work.dtd
<!-- The root container for any abstract art or structured publication -->
<!ELEMENT work (publication | ANY)>

<!-- Use this structure when the 'work' is specifically a document -->
<!ELEMENT publication (title, description, (series+ | book+))>
<!ATTLIST publication id ID #REQUIRED>

<!-- At least one of DOI or ISBN is required for a Series -->
<!ELEMENT series (title, description, ((doi, isbn?) | (isbn, doi?)), license, tags, date, front_matter?, books, pdf?, openalex?)>
<!ATTLIST series id CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT doi (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT tags (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT pdf (#PCDATA)>
<!ELEMENT openalex (#PCDATA)>

<!ELEMENT front_matter (chapter+)>
<!ELEMENT books (book+)>

<!-- At least one of DOI or ISBN is required for a Book -->
<!ELEMENT book (title, description?, ((doi, isbn?) | (isbn, doi?)), license?, tags?, date?, front_matter?, chapters)>
<!ATTLIST book id CDATA #REQUIRED>

<!ELEMENT chapters (chapter+)>

<!-- Chapters stay flexible with optional IDs -->
<!ELEMENT chapter (title, wiki?, source?, pdf?, doi?, openalex?, tags?)>
<!ATTLIST chapter id CDATA #IMPLIED>

<!ELEMENT wiki (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT pdf (#PCDATA)>
<!ELEMENT openalex (#PCDATA)>
<!ELEMENT tags (#PCDATA)>

=== TIBHannover/climate-knowledge-graph/data-import/work.xml
<?xml version="1.0" ?>
<!DOCTYPE work SYSTEM "work.dtd">
<work>
  <publication id="IPCC_AR6">
    <title>IPCC Sixth Assessment Report</title>
      <series id="IPCC_AR6_WGII">
        <title>Working Group II: Climate Change 2022 – Impacts, Adaptation and Vulnerability</title>
        <description>Climate Change 2022 – Impacts, Adaptation and Vulnerability</description>
        <doi>10.1017/9781009325844</doi>
        <license>CC-BY-NC-ND 4.0</license>
        <tags>Climate change; Global warming; Climate</tags>
        <date>2023-06-22</date>
        <front_matter>
          <chapter>
            <title>Summary for Policymakers</title>
            <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Summary-for-policymakers</wiki>
            <source>https://www.ipcc.ch/report/ar6/wg2/chapter/summary-for-policymakers/</source>
            <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_SummaryForPolicymakers.pdf</pdf>
            <doi>10.1017/9781009325844.001</doi>
            <openalex>W4382363608</openalex>
          </chapter>
          <chapter>
            <title>Technical Summary</title>
            <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Technical-summary</wiki>
            <source>https://www.ipcc.ch/report/ar6/wg2/chapter/technical-summary/</source>
            <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_TechnicalSummary.pdf</pdf>
            <doi>10.1017/9781009325844.002</doi>
            <openalex>W4382363579</openalex>
          </chapter>
        </front_matter>
        <books>
          <book id="1">
            <title>Chapters</title>
            <chapters>
              <chapter id="1">
                <title>Point of Departure and Key Concepts</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-1</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-1/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter01.pdf</pdf>
                <doi>10.1017/9781009325844.003</doi>
                <openalex>W4382362865</openalex>
              </chapter>
              <chapter id="2">
                <title>Terrestrial and Freshwater Ecosystems and Their Services</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-2</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-2/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter02.pdf</pdf>
                <doi>10.1017/9781009325844.004</doi>
                <openalex>W4382363505</openalex>
              </chapter>
              <chapter id="3">
                <title>Oceans and Coastal Ecosystems and Their Services</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-3</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-3/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter03.pdf</pdf>
                <doi>10.1017/9781009325844.005</doi>
                <openalex>W4382363666</openalex>
              </chapter>
              <chapter id="4">
                <title>Water</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-4</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-4/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter04.pdf</pdf>
                <doi>10.1017/9781009325844.006</doi>
                <openalex>W4382363526</openalex>
              </chapter>
              <chapter id="5">
                <title>Food, Fibre and Other Ecosystem Products</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-5</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-5/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter05.pdf</pdf>
                <doi>10.1017/9781009325844.007</doi>
                <openalex>W4382363604</openalex>
              </chapter>
              <chapter id="6">
                <title>Cities, Settlements and Key Infrastructure</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-6</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-6/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter06.pdf</pdf>
                <doi>10.1017/9781009325844.008</doi>
                <openalex>W4382363503</openalex>
              </chapter>
              <chapter id="7">
                <title>Health, Wellbeing and the Changing Structure of Communities</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-7</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-7/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter07.pdf</pdf>
                <doi>10.1017/9781009325844.009</doi>
                <openalex>W4382361937</openalex>
              </chapter>
              <chapter id="8">
                <title>Poverty, Livelihoods and Sustainable Development</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-8</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-8/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter08.pdf</pdf>
                <doi>10.1017/9781009325844.010</doi>
                <openalex>W2991859140</openalex>
              </chapter>
              <chapter id="9">
                <title>Africa</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-9</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-9/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter09.pdf</pdf>
                <doi>10.1017/9781009325844.011</doi>
                <openalex>W4382361932</openalex>
              </chapter>
              <chapter id="10">
                <title>Asia</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-10</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-10/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter10.pdf</pdf>
                <doi>10.1017/9781009325844.012</doi>
                <openalex>W4382362799</openalex>
              </chapter>
              <chapter id="11">
                <title>Australasia</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-11</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-11/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter11.pdf</pdf>
                <doi>10.1017/9781009325844.013</doi>
                <openalex>W4382363397</openalex>
              </chapter>
              <chapter id="12">
                <title>Central and South America</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-12</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-12/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter12.pdf</pdf>
                <doi>10.1017/9781009325844.014</doi>
                <openalex>W3109144505</openalex>
              </chapter>
              <chapter id="13">
                <title>Europe</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-13</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-13/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter13.pdf</pdf>
                <doi>10.1017/9781009325844.015</doi>
                <openalex>W4382363568</openalex>
              </chapter>
              <chapter id="14">
                <title>North America</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-14</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-14/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter14.pdf</pdf>
                <doi>10.1017/9781009325844.016</doi>
                <openalex>W4382363059</openalex>
              </chapter>
              <chapter id="15">
                <title>Small Islands</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-15</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-15/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter15.pdf</pdf>
                <doi>10.1017/9781009325844.017</doi>
                <openalex>W4382363037</openalex>
              </chapter>
              <chapter id="16">
                <title>Key Risks across Sectors and Regions</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-16</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-16/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter16.pdf</pdf>
                <doi>10.1017/9781009325844.025</doi>
                <openalex>W4382362903</openalex>
              </chapter>
              <chapter id="17">
                <title>Decision-Making Options for Managing Risk</title>
                <wiki>https://test.kewl.org/wiki/IPCC:Wg2:Chapter:Chapter-17</wiki>
                <source>https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-17/</source>
                <pdf>https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter17.pdf</pdf>
